"""add_webhook_subscription_model

Revision ID: 9fef252debfb
Revises: add_orders_account_unique
Create Date: 2026-02-09 15:27:08.837168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fef252debfb'
down_revision = 'add_orders_account_unique'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = set(inspector.get_table_names())
    if "shopify_integrations" not in tables:
        op.create_table('shopify_integrations',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('shop_domain', sa.String(), nullable=False),
        sa.Column('access_token', sa.String(), nullable=False),
        sa.Column('scopes', sa.String(), nullable=True),
        sa.Column('app_secret_encrypted', sa.String(), nullable=True),
        sa.Column('installed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('last_synced_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        tables.add("shopify_integrations")
    existing_indexes = set()
    if "shopify_integrations" in tables:
        existing_indexes = {idx["name"] for idx in inspector.get_indexes("shopify_integrations")}
    shopify_index_name = op.f('ix_shopify_integrations_shop_domain')
    if shopify_index_name not in existing_indexes:
        if conn.dialect.name == "postgresql":
            op.execute(
                f"CREATE UNIQUE INDEX IF NOT EXISTS {shopify_index_name} "
                "ON shopify_integrations (shop_domain)"
            )
        else:
            try:
                op.create_index(shopify_index_name, 'shopify_integrations', ['shop_domain'], unique=True)
            except Exception:
                pass
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('shop_domain', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('webhook_id', sa.String(), nullable=True),
    sa.Column('endpoint_url', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_delivery_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'shop_domain', 'topic', name='uq_webhook_subscription_user_source_shop_topic')
    )
    op.create_index(op.f('ix_webhook_subscriptions_shop_domain'), 'webhook_subscriptions', ['shop_domain'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_source'), 'webhook_subscriptions', ['source'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_topic'), 'webhook_subscriptions', ['topic'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_user_id'), 'webhook_subscriptions', ['user_id'], unique=False)
    op.drop_index('ix_order_profit_order_id', table_name='order_profit')
    op.alter_column('shipment_tracking', 'raw_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    sku_unique_constraints = {c["name"] for c in inspector.get_unique_constraints("sku_costs")}
    if "sku_costs_sku_key" in sku_unique_constraints:
        if conn.dialect.name == "postgresql":
            op.execute("ALTER TABLE sku_costs DROP CONSTRAINT IF EXISTS sku_costs_sku_key")
        else:
            op.drop_constraint('sku_costs_sku_key', 'sku_costs', type_='unique')
    op.drop_index('ix_sku_costs_sku', table_name='sku_costs')
    op.create_index(op.f('ix_sku_costs_sku'), 'sku_costs', ['sku'], unique=True)
    sync_jobs_columns = {col["name"] for col in inspector.get_columns("sync_jobs")}
    if "records_processed" not in sync_jobs_columns:
        if conn.dialect.name == "postgresql":
            op.execute("ALTER TABLE sync_jobs ADD COLUMN IF NOT EXISTS records_processed INTEGER")
        else:
            op.add_column('sync_jobs', sa.Column('records_processed', sa.Integer(), nullable=True))
    if "records_failed" not in sync_jobs_columns:
        if conn.dialect.name == "postgresql":
            op.execute("ALTER TABLE sync_jobs ADD COLUMN IF NOT EXISTS records_failed INTEGER")
        else:
            op.add_column('sync_jobs', sa.Column('records_failed', sa.Integer(), nullable=True))
    if "error_message" not in sync_jobs_columns:
        if conn.dialect.name == "postgresql":
            op.execute("ALTER TABLE sync_jobs ADD COLUMN IF NOT EXISTS error_message VARCHAR")
        else:
            op.add_column('sync_jobs', sa.Column('error_message', sa.String(), nullable=True))
    op.drop_index('ix_webhook_events_created_at', table_name='webhook_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_webhook_events_created_at', 'webhook_events', ['created_at'], unique=False)
    op.drop_column('sync_jobs', 'error_message')
    op.drop_column('sync_jobs', 'records_failed')
    op.drop_column('sync_jobs', 'records_processed')
    op.drop_index(op.f('ix_sku_costs_sku'), table_name='sku_costs')
    op.create_index('ix_sku_costs_sku', 'sku_costs', ['sku'], unique=False)
    op.create_unique_constraint('sku_costs_sku_key', 'sku_costs', ['sku'])
    op.alter_column('shipment_tracking', 'raw_response',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_order_profit_order_id', 'order_profit', ['order_id'], unique=False)
    op.drop_index(op.f('ix_webhook_subscriptions_user_id'), table_name='webhook_subscriptions')
    op.drop_index(op.f('ix_webhook_subscriptions_topic'), table_name='webhook_subscriptions')
    op.drop_index(op.f('ix_webhook_subscriptions_source'), table_name='webhook_subscriptions')
    op.drop_index(op.f('ix_webhook_subscriptions_shop_domain'), table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index(op.f('ix_shopify_integrations_shop_domain'), table_name='shopify_integrations')
    op.drop_table('shopify_integrations')
    # ### end Alembic commands ###
