"""add_customer_id_to_orders

Revision ID: e076b7128e37
Revises: e078ece594f2
Create Date: 2026-02-09 17:08:08.939660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e076b7128e37'
down_revision = 'e078ece594f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customer_id')
    # ### end Alembic commands ###
