"""add_order_finance_engine

Revision ID: e078ece594f2
Revises: 9fef252debfb
Create Date: 2026-02-09 16:49:16.533616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e078ece594f2'
down_revision = '9fef252debfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = set(inspector.get_table_names())
    
    # Create enum types if they don't exist
    if conn.dialect.name == "postgresql":
        try:
            conn.execute(sa.text("CREATE TYPE risktag AS ENUM ('SAFE', 'MEDIUM', 'HIGH')"))
        except Exception:
            pass  # Enum already exists
        try:
            conn.execute(sa.text("CREATE TYPE paymenttype AS ENUM ('PREPAID', 'COD')"))
        except Exception:
            pass  # Enum already exists
        try:
            conn.execute(sa.text("CREATE TYPE fulfilmentstatus AS ENUM ('DELIVERED', 'RTO', 'CANCELLED', 'IN_TRANSIT')"))
        except Exception:
            pass  # Enum already exists
        try:
            conn.execute(sa.text("CREATE TYPE profitstatus AS ENUM ('PROFIT', 'LOSS')"))
        except Exception:
            pass  # Enum already exists
    
    # Create customer_risk table if it doesn't exist
    if "customer_risk" not in tables:
        op.create_table('customer_risk',
        sa.Column('customer_id', sa.String(), nullable=False),
        sa.Column('total_orders', sa.Integer(), nullable=False),
        sa.Column('rto_count', sa.Integer(), nullable=False),
        sa.Column('loss_amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('risk_tag', sa.Enum('SAFE', 'MEDIUM', 'HIGH', name='risktag'), nullable=False),
        sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('last_order_date', sa.Date(), nullable=True),
        sa.Column('last_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('customer_id')
        )
    
    # Create order_finance table if it doesn't exist
    if "order_finance" not in tables:
        op.create_table('order_finance',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('order_id', sa.String(), nullable=False),
        sa.Column('order_value', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('revenue_realized', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('payment_type', sa.Enum('PREPAID', 'COD', name='paymenttype'), nullable=False),
        sa.Column('fulfilment_status', sa.Enum('DELIVERED', 'RTO', 'CANCELLED', 'IN_TRANSIT', name='fulfilmentstatus'), nullable=False),
        sa.Column('total_expense', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('net_profit', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('profit_status', sa.Enum('PROFIT', 'LOSS', name='profitstatus'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        
        # Create index only if it doesn't exist
        existing_indexes = {idx["name"] for idx in inspector.get_indexes("order_finance")}
        if "ix_order_finance_order_id" not in existing_indexes:
            op.create_index(op.f('ix_order_finance_order_id'), 'order_finance', ['order_id'], unique=True)
    
    # Create order_expenses table if it doesn't exist
    if "order_expenses" not in tables:
        # Create remaining enums if needed
        if conn.dialect.name == "postgresql":
            try:
                conn.execute(sa.text("CREATE TYPE expensetype AS ENUM ('FIXED', 'ADS', 'FWD_SHIP', 'REV_SHIP', 'GATEWAY', 'COD_FEE', 'OVERHEAD')"))
            except Exception:
                pass  # Enum already exists
            try:
                conn.execute(sa.text("CREATE TYPE expensesource AS ENUM ('MANUAL', 'API', 'SYSTEM')"))
            except Exception:
                pass  # Enum already exists
            try:
                conn.execute(sa.text("CREATE TYPE settlementstatus AS ENUM ('PENDING', 'SETTLED', 'OVERDUE')"))
            except Exception:
                pass  # Enum already exists
        
        op.create_table('order_expenses',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('order_id', sa.String(), nullable=False),
        sa.Column('order_finance_id', sa.String(), nullable=False),
        sa.Column('type', sa.Enum('FIXED', 'ADS', 'FWD_SHIP', 'REV_SHIP', 'GATEWAY', 'COD_FEE', 'OVERHEAD', name='expensetype'), nullable=False),
        sa.Column('source', sa.Enum('MANUAL', 'API', 'SYSTEM', name='expensesource'), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('effective_date', sa.Date(), nullable=False),
        sa.Column('editable', sa.Boolean(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['order_finance_id'], ['order_finance.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        
        # Create indexes only if they don't exist
        existing_expenses_indexes = {idx["name"] for idx in inspector.get_indexes("order_expenses")}
        if "ix_order_expenses_order_finance_id" not in existing_expenses_indexes:
            op.create_index(op.f('ix_order_expenses_order_finance_id'), 'order_expenses', ['order_finance_id'], unique=False)
        if "ix_order_expenses_order_id" not in existing_expenses_indexes:
            op.create_index(op.f('ix_order_expenses_order_id'), 'order_expenses', ['order_id'], unique=False)
    
    # Create order_settlements table if it doesn't exist
    if "order_settlements" not in tables:
        op.create_table('order_settlements',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('order_id', sa.String(), nullable=False),
        sa.Column('order_finance_id', sa.String(), nullable=False),
        sa.Column('partner', sa.String(), nullable=False),
        sa.Column('expected_date', sa.Date(), nullable=False),
        sa.Column('actual_date', sa.Date(), nullable=True),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'SETTLED', 'OVERDUE', name='settlementstatus'), nullable=False),
        sa.Column('reference_id', sa.String(), nullable=True),
        sa.Column('notes', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['order_finance_id'], ['order_finance.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        
        # Create indexes only if they don't exist
        existing_settlements_indexes = {idx["name"] for idx in inspector.get_indexes("order_settlements")}
        if "ix_order_settlements_order_finance_id" not in existing_settlements_indexes:
            op.create_index(op.f('ix_order_settlements_order_finance_id'), 'order_settlements', ['order_finance_id'], unique=False)
        if "ix_order_settlements_order_id" not in existing_settlements_indexes:
            op.create_index(op.f('ix_order_settlements_order_id'), 'order_settlements', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_settlements_order_id'), table_name='order_settlements')
    op.drop_index(op.f('ix_order_settlements_order_finance_id'), table_name='order_settlements')
    op.drop_table('order_settlements')
    op.drop_index(op.f('ix_order_expenses_order_id'), table_name='order_expenses')
    op.drop_index(op.f('ix_order_expenses_order_finance_id'), table_name='order_expenses')
    op.drop_table('order_expenses')
    op.drop_index(op.f('ix_order_finance_order_id'), table_name='order_finance')
    op.drop_table('order_finance')
    op.drop_table('customer_risk')
    # ### end Alembic commands ###
