"""add_order_finance_engine

Revision ID: e078ece594f2
Revises: 983762c6e925
Create Date: 2026-02-09 16:49:16.533616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e078ece594f2'
down_revision = '983762c6e925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = set(inspector.get_table_names())
    
    # Create enum types if they don't exist
    if conn.dialect.name == "postgresql":
        # Use PostgreSQL's DO block to create enums safely
        conn.execute(sa.text("""
            DO $$ BEGIN
                CREATE TYPE risktag AS ENUM ('SAFE', 'MEDIUM', 'HIGH');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """))
        conn.execute(sa.text("""
            DO $$ BEGIN
                CREATE TYPE paymenttype AS ENUM ('PREPAID', 'COD');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """))
        conn.execute(sa.text("""
            DO $$ BEGIN
                CREATE TYPE fulfilmentstatus AS ENUM ('DELIVERED', 'RTO', 'CANCELLED', 'IN_TRANSIT');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """))
        conn.execute(sa.text("""
            DO $$ BEGIN
                CREATE TYPE profitstatus AS ENUM ('PROFIT', 'LOSS');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """))
    
    # Create customer_risk table if it doesn't exist
    if "customer_risk" not in tables:
        # Use raw SQL to avoid enum creation issues
        conn.execute(sa.text("""
            CREATE TABLE IF NOT EXISTS customer_risk (
                customer_id VARCHAR NOT NULL PRIMARY KEY,
                total_orders INTEGER NOT NULL,
                rto_count INTEGER NOT NULL,
                loss_amount NUMERIC(12, 2) NOT NULL,
                risk_tag VARCHAR NOT NULL,
                risk_score NUMERIC(5, 2) NOT NULL,
                last_order_date DATE,
                last_updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
            )
        """))
        
        # Create indexes
        conn.execute(sa.text("""
            CREATE INDEX IF NOT EXISTS ix_customer_risk_risk_tag ON customer_risk(risk_tag)
        """))
        conn.execute(sa.text("""
            CREATE INDEX IF NOT EXISTS ix_customer_risk_last_order_date ON customer_risk(last_order_date)
        """))
    
    # Create order_finance table if it doesn't exist
    if "order_finance" not in tables:
        # Use raw SQL to avoid enum creation issues
        conn.execute(sa.text("""
            CREATE TABLE IF NOT EXISTS order_finance (
                id VARCHAR NOT NULL PRIMARY KEY,
                order_id VARCHAR NOT NULL,
                order_value NUMERIC(12, 2) NOT NULL,
                revenue_realized NUMERIC(12, 2) NOT NULL,
                payment_type VARCHAR NOT NULL,
                fulfilment_status VARCHAR NOT NULL,
                total_expense NUMERIC(12, 2) NOT NULL,
                net_profit NUMERIC(12, 2) NOT NULL,
                profit_status VARCHAR NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
                FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
            )
        """))
        
        # Create index only if it doesn't exist
        existing_indexes = {idx["name"] for idx in inspector.get_indexes("order_finance")}
        if "ix_order_finance_order_id" not in existing_indexes:
            op.create_index(op.f('ix_order_finance_order_id'), 'order_finance', ['order_id'], unique=True)
    
    # Create order_expenses table if it doesn't exist
    if "order_expenses" not in tables:
        # Use raw SQL to avoid enum creation issues
        conn.execute(sa.text("""
            CREATE TABLE IF NOT EXISTS order_expenses (
                id VARCHAR NOT NULL PRIMARY KEY,
                order_id VARCHAR NOT NULL,
                order_finance_id VARCHAR NOT NULL,
                type VARCHAR NOT NULL,
                source VARCHAR NOT NULL,
                amount NUMERIC(12, 2) NOT NULL,
                effective_date DATE NOT NULL,
                editable BOOLEAN NOT NULL,
                description VARCHAR,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
                FOREIGN KEY (order_finance_id) REFERENCES order_finance(id) ON DELETE CASCADE,
                FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
            )
        """))
        
        # Create indexes only if they don't exist
        existing_expenses_indexes = {idx["name"] for idx in inspector.get_indexes("order_expenses")}
        if "ix_order_expenses_order_finance_id" not in existing_expenses_indexes:
            op.create_index(op.f('ix_order_expenses_order_finance_id'), 'order_expenses', ['order_finance_id'], unique=False)
        if "ix_order_expenses_order_id" not in existing_expenses_indexes:
            op.create_index(op.f('ix_order_expenses_order_id'), 'order_expenses', ['order_id'], unique=False)
    
    # Create order_settlements table if it doesn't exist
    if "order_settlements" not in tables:
        # Use raw SQL to avoid enum creation issues
        conn.execute(sa.text("""
            CREATE TABLE IF NOT EXISTS order_settlements (
                id VARCHAR NOT NULL PRIMARY KEY,
                order_id VARCHAR NOT NULL,
                order_finance_id VARCHAR NOT NULL,
                partner VARCHAR NOT NULL,
                expected_date DATE NOT NULL,
                actual_date DATE,
                amount NUMERIC(12, 2) NOT NULL,
                status VARCHAR NOT NULL,
                reference_id VARCHAR,
                notes VARCHAR,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
                FOREIGN KEY (order_finance_id) REFERENCES order_finance(id) ON DELETE CASCADE,
                FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
            )
        """))
        
        # Create indexes only if they don't exist
        existing_settlements_indexes = {idx["name"] for idx in inspector.get_indexes("order_settlements")}
        if "ix_order_settlements_order_finance_id" not in existing_settlements_indexes:
            op.create_index(op.f('ix_order_settlements_order_finance_id'), 'order_settlements', ['order_finance_id'], unique=False)
        if "ix_order_settlements_order_id" not in existing_settlements_indexes:
            op.create_index(op.f('ix_order_settlements_order_id'), 'order_settlements', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_settlements_order_id'), table_name='order_settlements')
    op.drop_index(op.f('ix_order_settlements_order_finance_id'), table_name='order_settlements')
    op.drop_table('order_settlements')
    op.drop_index(op.f('ix_order_expenses_order_id'), table_name='order_expenses')
    op.drop_index(op.f('ix_order_expenses_order_finance_id'), table_name='order_expenses')
    op.drop_table('order_expenses')
    op.drop_index(op.f('ix_order_finance_order_id'), table_name='order_finance')
    op.drop_table('order_finance')
    op.drop_table('customer_risk')
    # ### end Alembic commands ###
